In [1]:
import numpy as np

In [2]:
a = np.asmatrix(np.arange(12).reshape(3, 4))
a

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [3]:
b = np.asmatrix(np.arange(12, 24).reshape(4, 3))
b

matrix([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])

In [4]:
a * b

matrix([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]])

In [5]:
a * a.T

matrix([[ 14,  38,  62],
        [ 38, 126, 214],
        [ 62, 214, 366]])

In [6]:
a.T * a

matrix([[ 80,  92, 104, 116],
        [ 92, 107, 122, 137],
        [104, 122, 140, 158],
        [116, 137, 158, 179]])